### ISSUE TITLE
Bewitchment/Caverns Conflict Crashes Server. Can't join world.

### ISSUE THREAD

**Issue by JoelZBub** [JoelZBub/organic-free-range-pack#4]
When encountering mobs in the Caverns Dimension, the server hard crashes with 

<details>
  <summary>Spoiler!</summary>
  `java.lang.NullPointerException: Null string not allowed
	at java.util.Objects.requireNonNull(Objects.java:228)
	at net.minecraft.nbt.NBTTagString.<init>(NBTTagString.java:19)
	at net.minecraft.nbt.NBTTagCompound.func_74778_a(NBTTagCompound.java:138)
	at net.minecraft.entity.Entity.serializeNBT(Entity.java:3132)
	at com.bewitchment.common.handler.MiscHandler.joinWorld(MiscHandler.java:68)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_1029_MiscHandler_joinWorld_EntityJoinWorldEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraft.world.World.func_72838_d(World.java:1206)
	at net.minecraft.world.WorldServer.func_72838_d(WorldServer.java:1058)
	at net.minecraft.entity.monster.AbstractSkeleton.func_82196_d(AbstractSkeleton.java:225)
	at cavern.entity.ai.EntityAIAttackCavenicBow.func_75246_d(EntityAIAttackCavenicBow.java:174)
	at net.minecraft.entity.ai.EntityAITasks.func_75774_a(SourceFile:129)`

</details>

**Comment by JoelZBub** [comment]
#https://github.com/Um-Mitternacht/Bewitchment/issues/438
#https://github.com/kegare/Cavern2/issues/46

**Comment by JoelZBub** [comment]
Solution: Remove Bewitchment
