### ISSUE TITLE
Enderutilities - Removing memory card with items from a SimpleStorageNetwork crashes.

### ISSUE THREAD

**Issue by dommrogers** [JoelZBub/organic-free-range-pack#54]
### Describe the Bug:
Storing an existing EnderUtilities memory card with items stored in it and then trying to remove that card from the SimpleStorageNetwork causes network issue which crashes the client back to server list.

### How Can We Reproduce the Bug:
1. Craft a "10 B" memory card from ender utilities
2. Store a fair amount of items (limit/threshold unknown, see screenshot)
3. Put it inside a Simple Storage Network
4. Try and remove the card using the Storage Request Table

### Expected behavior:
Card is removed and placed in the player inventory.

### If Applicable, Add Screenshots or Video to Explain the Bug:
![image](https://user-images.githubusercontent.com/707295/87428947-fc05c380-c5da-11ea-9dc7-7b32a991ce53.png)

### Crash Report or Game Log
NetworkDispatcher exception
java.lang.IllegalArgumentException: Payload may not be larger than 32767 bytes
	at net.minecraft.network.play.client.CPacketCustomPayload.<init>(CPacketCustomPayload.java:28)
	at net.minecraftforge.fml.common.network.internal.FMLProxyPacket.toC17Packet(FMLProxyPacket.java:142)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.write(NetworkDispatcher.java:533)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWrite0(AbstractChannelHandlerContext.java:738)
	at io.netty.channel.AbstractChannelHandlerContext.invokeWriteAndFlush(AbstractChannelHandlerContext.java:801)
	at io.netty.channel.AbstractChannelHandlerContext.write(AbstractChannelHandlerContext.java:814)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:794)
	at io.netty.channel.AbstractChannelHandlerContext.writeAndFlush(AbstractChannelHandlerContext.java:831)
	at io.netty.channel.DefaultChannelPipeline.writeAndFlush(DefaultChannelPipeline.java:1032)
	at io.netty.channel.AbstractChannel.writeAndFlush(AbstractChannel.java:296)
	at net.minecraft.network.NetworkManager$4.run(NetworkManager.java:245)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:403)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
	at java.lang.Thread.run(Thread.java:745)

### Please complete the following information:
 - Modpack Version Number : 1.0.1
 - Is OptiFine installed? : Yes
 - Does this issue affect Server, Client, or Both? : Client

STBlade o/

**Comment by dommrogers** [comment]
Somewhat redundent :), just cleaning up my GitHub
